GET http://localhost:8080/api/users 

### Get single user 
GET http://localhost:8080/api/users/63a93ed08e1a8f8f7dbb972a

### create single user 

POST http://localhost:8080/api/users/
Content-Type: application/json


{
  "firstName": "Ale",
  "lastName": "moges",
  "userName": "ale21",
  "password": "sabina12",
  "email": "sabamoges@gmail.com",
  "phoneNo": 912345678,
  "gender": "F",
  "profilePhoto": "https://www.asxbcty.com",
  "country": "Ethiopia",
  "state": "Addis Ababa",
  "title": "Full stack Web developer | Node | React | JavaScript | Html | CSS",
  "titleOverview": "Hello 👋 , I'm saba moges motivated Full-stack web developer  with 2+ years of experience. with excellent customer care, outstanding interpersonal communication and multitasking abilities.  Prepared to deliver first-rate results to clients on the allocated time and finish tasks before deadlines ⏰. 🏆  I am a young talented African sustaining strong motivation for work, and has skills with best practices. I can work collaboratively in different working environments and team compositions. also can work on modifying existing or adding new requirements to existing systems.",
  "previousWork": [
    {
      "workTitle": "Guzo : Ridesharing Platform",
      "workThumbnail": "",
      "workDescription": "Guzo is a ridesharing platform made by a team of 3 talented students",
      "workLink": "https://github.com/philica/Guzo-ridesharingPlatform",
      "workSkill": ["React", "json", "Js", "Node"],
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.605Z",
      "createdAt": "2022-12-15T18:35:56.606Z",
      "updatedAt": "2022-12-15T18:35:56.606Z"
    }
  ],
  "skill": [
    {
      
      "skillName": "React",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.607Z",
      "createdAt": "2022-12-15T18:35:56.608Z",
      "updatedAt": "2022-12-15T18:35:56.609Z"
    },
    {
     
      "skillName": "CSS",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.609Z",
      "createdAt": "2022-12-15T18:35:56.610Z",
      "updatedAt": "2022-12-15T18:35:56.610Z"
    },
    {
      
      "skillName": "Node",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.612Z",
      "createdAt": "2022-12-15T18:35:56.612Z",
      "updatedAt": "2022-12-15T18:35:56.612Z"
    }
  ],
  "language": [
    {
     
      "languageName": "Amharic",
      "languageProficiency": "Native",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.614Z",
      "createdAt": "2022-12-15T18:35:56.614Z",
      "updatedAt": "2022-12-15T18:35:56.615Z"
    },
    {
     
      "languageName": "oromifa",
      "languageProficiency": "basic",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.617Z",
      "createdAt": "2022-12-15T18:35:56.617Z",
      "updatedAt": "2022-12-15T18:35:56.618Z"
    }
  ],
  "education": [
    {
      
      "schoolName": "Addis Ketema Preparatory School",
      "dateAttended": "2022-12-15T18:35:56.619Z",
      "areaOfStudy": "computerscience",
      "eduDescription": "",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.619Z",
      "createdAt": "2022-12-15T18:35:56.619Z",
      "updatedAt": "2022-12-15T18:35:56.620Z"
    }
  ],
  "certification": [
    {
     
      "certPhoto": "https://asdfesd.com",
      "certTitle": "International Collegiate Programming Contest",
      "certProvider": "Icpc.foundation",
      "certLink": "",
      "dateIssued": "2022-12-15T18:35:56.622Z",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.622Z",
      "createdAt": "2022-12-15T18:35:56.622Z",
      "updatedAt": "2022-12-15T18:35:56.623Z"
    },
    {
      
      "certPhoto": "https://asdfesd.com",
      "certTitle": "CSS completion",
      "certProvider": "Icpc.foundation",
      "certLink": "",
      "dateIssued": "2022-12-15T18:35:56.627Z",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.627Z",
      "createdAt": "2022-12-15T18:35:56.627Z",
      "updatedAt": "2022-12-15T18:35:56.628Z"
    }
  ],
  "employmentHistory": [
    {
     
      "empAt": "",
      "empLocation": "",
      "empRole": "",
      "empPeriod": "",
      "empDescription": "",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.629Z",
      "createdAt": "2022-12-15T18:35:56.630Z",
      "updatedAt": "2022-12-15T18:35:56.630Z"
    }
  ],
  "otherExperience": [
    {
      
      "expSubject": "Seminar Subdivision Head",
      "expDescription": "I'm also currently serving as Seminar subdivision Head in our computer science and engineering club inside our college campus, we now have launched the first successful live seminar in different platforms like Zoom, YouTube and Telegram live",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.631Z",
      "createdAt": "2022-12-15T18:35:56.631Z",
      "updatedAt": "2022-12-15T18:35:56.632Z"
    },
    {
      
      "expSubject": "Podcast Production",
      "expDescription": "I am currently part of podcast subdivision in computer science and engineering club located in adama science and technology university  and also done 1 production level podcast as host with the great Mukerem Ali who is now  post graduate student and finished his undergraduate degree with CGPA of 4.0",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.633Z",
      "createdAt": "2022-12-15T18:35:56.634Z",
      "updatedAt": "2022-12-15T18:35:56.634Z"
    }
  ]
}


### Delete single user 

DELETE http://localhost:8080/api/users/63a93c88f7859fc076961bff

//check update route

### Get all previous work history

GET http://localhost:8080/api/users/previousWork/63a60fb23cfbc37ddfacc978

### Get single previous work history

GET http://localhost:8080/api/users/previousWork/63a60fb23cfbc37ddfacc978/63a60fb23cfbc37ddfacc979

### create new prevous work history

POST  http://localhost:8080/api/users/previousWork/63a60fb23cfbc37ddfacc978
Content-Type: application/json

{
  "workTitle": "spidy blogs ",
  "workThumbnail": "",
  "workDescription": "Spider is a blogging platform made by a team of 3 talented students",
  "workLink": "https://github.com/philica/Guzo-ridesharingPlatform",
  "workSkill": ["React", "CSS", "Js", "Node"],
  "isDeleted": 0,
  "deletedAt": "2022-12-15T18:35:56.605Z",
  "createdAt": "2022-12-15T18:35:56.606Z",
  "updatedAt": "2022-12-15T18:35:56.606Z"
}

### delete a single previous work history 

DELETE http://localhost:3000/users/previousWork/63a4ee908bc253b3856a0135/63a52c96b67a7cb24e1a8d72

### update previous work  history 

PATCH http://localhost:3000/users/previousWork/63a4ee908bc253b3856a0135/63a5f04bc4da69af17e737b9
Content-Type: application/json

{
  "workTitle": "Second updated blog ",
  "workThumbnail": "",
  "workDescription": "borggy is a blogging platform made by a team of 3 talented students",
  "workLink": "https://github.com/philica/Guzo-ridesharingPlatform",
  "workSkill": ["React", "CSS", "Js", "Node"],
  "isDeleted": 0,
  "deletedAt": "2022-12-15T18:35:56.605Z",
  "createdAt": "2022-12-15T18:35:56.606Z",
  "updatedAt": "2022-12-15T18:35:56.606Z"
}


### get all skill
GET http://localhost:8080/api/users/skill/63a60fb23cfbc37ddfacc978

### create a skill
PATCH  http://localhost:8080/api/users/skill/63a60fb23cfbc37ddfacc978
Content-Type: application/json

{
  "skill":[
    {
      "skillName": "React"  
    },
    {
      "skillName": "NodeJs" 
    },
    {
      "skillName": "MongoDB" 
    },
    {
      "skillName": "Frappe" 
    }
  ]
}

### get all languages
GET http://localhost:3000/users/language/63a60fb23cfbc37ddfacc978

### get single language
GET http://localhost:3000/users/language/63a60fb23cfbc37ddfacc978/63a60fb23cfbc37ddfacc97d

### create new prevous work history

POST http://localhost:3000/users/language/63a60fb23cfbc37ddfacc978
Content-Type: application/json

{
   "languageName":"Korean",
   "languageProficiency":"Native",
   "isDeleted":0,
   "deletedAt":"2022-12-15T18:35:56.614Z",
   "createdAt":"2022-12-15T18:35:56.614Z",
   "updatedAt":"2022-12-15T18:35:56.615Z"
} 

### delete language 
DELETE http://localhost:3000/users/language/63a60fb23cfbc37ddfacc978/63a9562635f310076319d8ab

### update language
PATCH  http://localhost:3000/users/language/63a60fb23cfbc37ddfacc978
Content-Type: application/json

{
  "language":[
        {
      "languageName": "Amharic",
      "languageProficiency": "Native",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.614Z",
      "createdAt": "2022-12-15T18:35:56.614Z",
      "updatedAt": "2022-12-15T18:35:56.615Z",
      "_id": "63a60fb23cfbc37ddfacc97d"
    },
    {
      "languageName": "Englifa",
      "languageProficiency": "basic",
      "isDeleted": 0,
      "deletedAt": "2022-12-15T18:35:56.617Z",
      "createdAt": "2022-12-15T18:35:56.617Z",
      "updatedAt": "2022-12-15T18:35:56.618Z",
      "_id": "63a60fb23cfbc37ddfacc97e"
    },
    {
      "languageName": "Korean",
      "languageProficiency": "Native",
      "_id": "63a9584de175d42abe013193"
    }
  ]
}



### get all education
GET http://localhost:3000/users/education/63a93ed08e1a8f8f7dbb972a

### get single education 
GET http://localhost:3000/users/education/63a60fb23cfbc37ddfacc978/63a60fb23cfbc37ddfacc97f

### create education

POST http://localhost:3000/users/education/63a93ed08e1a8f8f7dbb972a
Content-Type: application/json

{
   "schoolName":"cathedtal Preparatory School",
   "dateAttendedFrom":"2022-12-15T18:35:56.619Z",
   "dateAttendedTo":"2022-12-15T18:35:56.619Z",
   "areaOfStudy":"computerscience",
   "eduDescription":"hello there",
   "isDeleted":0,
   "deletedAt":"2022-12-15T18:35:56.614Z",
   "createdAt":"2022-12-15T18:35:56.614Z",
   "updatedAt":"2022-12-15T18:35:56.615Z"
}

### update education
PATCH http://localhost:3000/users/education/63a60fb23cfbc37ddfacc978/63a99bc5eff9ec765e5bdcdf 
Content-Type: application/json

{
  "schoolName":"cathedtal Preparatory School",
  "dateAttendedFrom":"2022-12-15T18:35:56.619Z",
  "dateAttendedTo":"2022-12-15T18:35:56.619Z",
  "areaOfStudy":"computerscience",
  "eduDescription":"hello there",
  "isDeleted":0,
  "deletedAt":"2022-12-15T18:35:56.614Z",
  "createdAt":"2022-12-15T18:35:56.614Z",
  "updatedAt":"2022-12-15T18:35:56.615Z"
}

### delete education 
DELETE http://localhost:3000/users/education/63a93ed08e1a8f8f7dbb972a/63a93ed08e1a8f8f7dbb9731


### get all certifications
GET http://localhost:3000/users/certification/63a93ed08e1a8f8f7dbb972a

### create certification 
POST http://localhost:3000/users/certification/63a93ed08e1a8f8f7dbb972a
Content-Type: application/json

{
  "certPhoto": "https://asdfesd.com",
  "certTitle": "Mongo db developer completion",
  "certProvider": "Icpc.foundation",
  "certLink": "req.body.certTitle",
  "dateIssued":"2022-12-15T18:35:56.627Z",
  "isDeleted": 0,
  "deletedAt": "2022-12-15T18:35:56.627Z",
  "createdAt":"2022-12-15T18:35:56.614Z",
  "updatedAt":"2022-12-15T18:35:56.615Z"
}

### update certification 
PATCH http://localhost:3000/users/certification/63a93ed08e1a8f8f7dbb972a/63ab36887dd55e8a058f642c
Content-Type: application/json

{
  "certPhoto": "https://mongy.com",
  "certTitle": "Mongo db developer completion",
  "certProvider": "Icpc.foundation",
  "certLink": "req.body.certTitle",
  "dateIssued":"2022-12-15T18:35:56.627Z",
  "isDeleted": 0,
  "deletedAt": "2022-12-15T18:35:56.627Z",
  "createdAt":"2022-12-15T18:35:56.614Z",
  "updatedAt":"2022-12-15T18:35:56.615Z"
}

### delete certification  
DELETE http://localhost:3000/users/certification/63a93ed08e1a8f8f7dbb972a/63ab3e2994fe4d29a4564c75


### get all employmentHistory
GET http://localhost:3000/users/employmentHistory/63a93ed08e1a8f8f7dbb972a


###create employmentHistory 
POST http://localhost:3000/users/employmentHistory/63a93ed08e1a8f8f7dbb972a
Content-Type: application/json

{
  "empAt": "Across Express",
  "empLocation": "Megenagna",
  "empRole": "Frontend Developer",
  "empPeriod": "3month",
  "empDescription": "Frappe and Erp Next developer",
  "isDeleted": 0,
  "deletedAt": "2022-12-15T18:35:56.629Z",
  "createdAt":"2022-12-15T18:35:56.614Z",
  "updatedAt":"2022-12-15T18:35:56.615Z"
}

### update employmentHistory 
PATCH http://localhost:3000/users/employmentHistory/63a93ed08e1a8f8f7dbb972a/63ab4f74e5a6cb8ee5f0303c
Content-Type: application/json

{
  "empAt": "Rahove Technologies",
  "empLocation": "Megenagna",
  "empRole": "Frontend Developer",
  "empPeriod": "3month",
  "empDescription": "Frappe and Erp Next developer",
  "isDeleted": 0,
  "deletedAt": "2022-12-15T18:35:56.629Z",
  "createdAt":"2022-12-15T18:35:56.614Z",
  "updatedAt":"2022-12-15T18:35:56.615Z"
}

### delete employmentHistory  
DELETE http://localhost:3000/users/employmentHistory/63a93ed08e1a8f8f7dbb972a/63a93ed08e1a8f8f7dbb9734

### update profile info 

PATCH http://localhost:3000/users/personalInfo/63b13cfd127ade2c12562493
Content-Type: application/json

{
 "firstName":"alazar tfirst",
 "lastName":"Sabawi tlast",
 "country":"Kenya",
 "state":"Addis Ababa"
}